[project]
name = "aoc21"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pytest>=8.3.3",
    "python-lsp-server>=1.12.0",
]

